name: wasatpay-backend
services:
- name: api
  source_dir: /
  github:
    repo: your-github-username/wasatpay-backend
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py src.main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /api/health
  envs:
  - key: FLASK_ENV
    value: production
  - key: SECRET_KEY
    type: SECRET
    value: your-secret-key-here
  - key: DATABASE_URL
    type: SECRET
    value: ${db.DATABASE_URL}
  - key: MAIL_SERVER
    value: smtp.sendgrid.net
  - key: MAIL_PORT
    value: "587"
  - key: MAIL_USE_TLS
    value: "true"
  - key: MAIL_USERNAME
    type: SECRET
    value: apikey
  - key: MAIL_PASSWORD
    type: SECRET
    value: your-sendgrid-api-key
  - key: MAIL_DEFAULT_SENDER
    value: noreply@wasatpay.com
  - key: STRIPE_PUBLISHABLE_KEY
    type: SECRET
    value: your-stripe-publishable-key
  - key: STRIPE_SECRET_KEY
    type: SECRET
    value: your-stripe-secret-key
  - key: FLUTTERWAVE_PUBLIC_KEY
    type: SECRET
    value: your-flutterwave-public-key
  - key: FLUTTERWAVE_SECRET_KEY
    type: SECRET
    value: your-flutterwave-secret-key
  - key: CORS_ORIGINS
    value: "*"

databases:
- name: db
  engine: PG
  version: "14"
  size: basic
  num_nodes: 1

domains:
- domain: wasatpay.com
  type: PRIMARY
  wildcard: false
  zone: wasatpay.com

